version: '3.4'

services:
  referencedb:
    image: mongo

  reference.api:
    image: ${DOCKER_REGISTRY-}referenceapi
    build:
      context: .
      dockerfile: service/reference/Reference.API/Dockerfile
volumes:
  mongo_data: