version: '3.4'

services:
  referencedb:
    container_name: referencedb
    restart:  always
    ports:
     - "27017:27017"
    volumes:
        - mongo_data:/data/db

  issuetrackerdb:
    container_name: issuetrackerdb
    environment:
        SA_PASSWORD: "SwN12345678"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"


  reference.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://referencedb:27017"
    depends_on:
      - referencedb
    ports:
      - "8000:80"

